function generateSecurePassword(): string {
  const saints = [
    'SantoAntonio',
    'SantaMaria',
    'SaoPedro',
    'SaoJoao',
    'SantaBarbara',
    'SaoPaulo',
    'SaoFrancisco',
    'SantaTereza',
    'SantaClara',
    'PadreCicero',
    'SantaTerezinha',
    'SaoBento',
    'SaoDomingos',
    'SaoJorge',
    'SantaCatarina',
    'SaoTomas',
    'SaoLucas',
    'SaoMateus',
    'SaoMarcos',
    'SaoTiago',
    'SantaAna',
    'SaoJose',
    'SaoMartinho',
    'SaoFilipe',
    'SantaRita',
    'SantaIsabel',
    'SaoJoaoPauloII',
    'SantaFaustina',
    'SantaEdwiges',
    'SaoInacio',
    'SaoFranciscoXavier',
    'SaoVitor',
    'SantoElias',
    'SantaLuzia',
    'SantaMargarete',
    'SaoValentim',
    'SantaVeronica',
    'SantoEstanislau',
    'SantaMonica',
    'SaoAgostinho',
    'SantaPaulina',
    'SaoTarcisio',
    'SaoRafael',
    'SaoGabriel',
    'SaoMiguel',
    'SantaSofia',
    'SaoBernardo',
    'SaoBonifacio',
    'SantaGertrudes',
    'SantaEufrasia',
    'SantoHermenegildo',
    'SantaEulalia',
    'SaoSeverino',
    'SantoEfrém',
    'SantaJoana',
    'SantaLeopoldina',
    'SantaFilomena',
    'SaoRicardo',
    'SantoAmaro',
    'SaoCarlosBorromeu',
    'SantaAgatha',
    'SantoAdriano',
    'SantaCristina',
    'SantaHelena',
    'SantaPerpetua',
    'SantaFelicidade',
    'SantoAnselmo',
    'SantaGenoveva',
    'SaoNicolau',
    'SantaJustina',
    'SantaInes',
    'SantoClemente',
    'SaoCalisto',
    'SaoCornelio',
    'SaoFabiano',
    'SaoGelasio',
    'SantaCecilia',
    'SantaMarcelina',
    'SantaTeresaDeCalcutá',
    'SaoPioDePietrelcina',
    'SantaBernadette',
    'SaoMaximilianoKolbe',
    'SantaGiannaBerettaMolla',
    'SantaEscolastica',
    'SantaAnastacia',
    'SaoVenceslau',
    'SantaEugenia',
    'SaoLonguinho',
    'SantaMatilde',
    'SaoGerardo',
    'SaoLourenco',
    'SantaTarcila',
    'SantaRafaela',
    'SantaUrsula',
    'SantaMarina',
    'SantaJulia',
    'SaoExpedito',
    'SantaEster',
    'SantaMelania',
    'SaoLadislao',
    'SaoFlorencio',
    'SantaSalome',
    'SantaDoroteia',
    'SaoNorberto',
    'SantaTecla',
    'SantaRufina',
    'SantaIngracia',
    'SaoWilfrido',
    'SantaAdelaide',
    'SantaMarcela',
    'SantaMargaridaMaria',
    'SantaAlacoque',
    'SantaOtilia',
    'SantaBrígida',
    'SaoCasimiro',
    'SantaErmelinda',
    'SantoEduardo',
    'SantaAquilina',
    'SaoLeaoMagno',
    'SantaPlacida',
    'SantaColeta',
    'SantaEugeniaDeRoma',
    'SantaAbadia',
    'SaoBasílio',
    'SantaAnaRosa',
    'SantaTeresaDosAndes',
    'SantaAngelaDeFoligno',
  ]

  const year = new Date().getFullYear() // Pega o ano atual
  const randomDigits = Math.floor(100 + Math.random() * 900) // Gera um número
  // aleatório de 3 dígitos (100 a 999)
  const randomSanto = saints[Math.floor(Math.random() * saints.length)]

  // Insere o número de 3 dígitos no meio do nome do santo
  const santoPart1 = randomSanto.substring(0, randomSanto.length / 2)
  const santoPart2 = randomSanto.substring(randomSanto.length / 2)
  const password = `${santoPart1}${randomDigits}${santoPart2}@${year}`

  return password
}

export default generateSecurePassword
