/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AvatarMenu: typeof import('./components/User/AvatarMenu.vue')['default']
    Editor: typeof import('./components/Documents/Editor.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NotificationMenu: typeof import('./components/User/NotificationMenu.vue')['default']
    PDFList: typeof import('./components/Documents/PDFList.vue')['default']
    PDFUpload: typeof import('./components/Documents/PDFUpload.vue')['default']
    PDFViewer: typeof import('./components/Documents/PDFViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SoftagonIcon: typeof import('./components/SoftagonIcon.vue')['default']
  }
}
