/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/Administracao': RouteRecordInfo<'/admin/Administracao', '/admin/Administracao', Record<never, never>, Record<never, never>>,
    '/admin/Ajuda': RouteRecordInfo<'/admin/Ajuda', '/admin/Ajuda', Record<never, never>, Record<never, never>>,
    '/admin/Assinaturas': RouteRecordInfo<'/admin/Assinaturas', '/admin/Assinaturas', Record<never, never>, Record<never, never>>,
    '/admin/Dashboard': RouteRecordInfo<'/admin/Dashboard', '/admin/Dashboard', Record<never, never>, Record<never, never>>,
    '/admin/Documentos': RouteRecordInfo<'/admin/Documentos', '/admin/Documentos', Record<never, never>, Record<never, never>>,
    '/admin/Fluxos': RouteRecordInfo<'/admin/Fluxos', '/admin/Fluxos', Record<never, never>, Record<never, never>>,
    '/admin/Notificacoes': RouteRecordInfo<'/admin/Notificacoes', '/admin/Notificacoes', Record<never, never>, Record<never, never>>,
    '/admin/Relatorios': RouteRecordInfo<'/admin/Relatorios', '/admin/Relatorios', Record<never, never>, Record<never, never>>,
    '/admin/teste': RouteRecordInfo<'/admin/teste', '/admin/teste', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
  }
}
