/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/administracao/ConfiguracoesSistema': RouteRecordInfo<'/admin/administracao/ConfiguracoesSistema', '/admin/administracao/ConfiguracoesSistema', Record<never, never>, Record<never, never>>,
    '/admin/administracao/GerenciamentoUsuarios': RouteRecordInfo<'/admin/administracao/GerenciamentoUsuarios', '/admin/administracao/GerenciamentoUsuarios', Record<never, never>, Record<never, never>>,
    '/admin/assinaturas/AssinaturaDocumentos': RouteRecordInfo<'/admin/assinaturas/AssinaturaDocumentos', '/admin/assinaturas/AssinaturaDocumentos', Record<never, never>, Record<never, never>>,
    '/admin/assinaturas/GerenciarCertificados': RouteRecordInfo<'/admin/assinaturas/GerenciarCertificados', '/admin/assinaturas/GerenciarCertificados', Record<never, never>, Record<never, never>>,
    '/admin/assinaturas/ValidacaoAssinaturas': RouteRecordInfo<'/admin/assinaturas/ValidacaoAssinaturas', '/admin/assinaturas/ValidacaoAssinaturas', Record<never, never>, Record<never, never>>,
    '/admin/dashboard/': RouteRecordInfo<'/admin/dashboard/', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    '/admin/documentos/CriarDocumento': RouteRecordInfo<'/admin/documentos/CriarDocumento', '/admin/documentos/CriarDocumento', Record<never, never>, Record<never, never>>,
    '/admin/documentos/DocumentosEnviados': RouteRecordInfo<'/admin/documentos/DocumentosEnviados', '/admin/documentos/DocumentosEnviados', Record<never, never>, Record<never, never>>,
    '/admin/documentos/DocumentosRecebidos': RouteRecordInfo<'/admin/documentos/DocumentosRecebidos', '/admin/documentos/DocumentosRecebidos', Record<never, never>, Record<never, never>>,
    '/admin/documentos/MeusDocumentos': RouteRecordInfo<'/admin/documentos/MeusDocumentos', '/admin/documentos/MeusDocumentos', Record<never, never>, Record<never, never>>,
    '/admin/fluxos/CriarFluxo': RouteRecordInfo<'/admin/fluxos/CriarFluxo', '/admin/fluxos/CriarFluxo', Record<never, never>, Record<never, never>>,
    '/admin/fluxos/HistoricoFluxos': RouteRecordInfo<'/admin/fluxos/HistoricoFluxos', '/admin/fluxos/HistoricoFluxos', Record<never, never>, Record<never, never>>,
    '/admin/fluxos/MeusFluxos': RouteRecordInfo<'/admin/fluxos/MeusFluxos', '/admin/fluxos/MeusFluxos', Record<never, never>, Record<never, never>>,
    '/admin/notificacoes/CentralNotificacoes': RouteRecordInfo<'/admin/notificacoes/CentralNotificacoes', '/admin/notificacoes/CentralNotificacoes', Record<never, never>, Record<never, never>>,
    '/admin/notificacoes/NotificacoesTempoReal': RouteRecordInfo<'/admin/notificacoes/NotificacoesTempoReal', '/admin/notificacoes/NotificacoesTempoReal', Record<never, never>, Record<never, never>>,
    '/admin/organization/departments/': RouteRecordInfo<'/admin/organization/departments/', '/admin/organization/departments', Record<never, never>, Record<never, never>>,
    '/admin/organization/departments/CreateDepartment': RouteRecordInfo<'/admin/organization/departments/CreateDepartment', '/admin/organization/departments/CreateDepartment', Record<never, never>, Record<never, never>>,
    '/admin/relatorios/Exportacao': RouteRecordInfo<'/admin/relatorios/Exportacao', '/admin/relatorios/Exportacao', Record<never, never>, Record<never, never>>,
    '/admin/relatorios/RelatoriosGerenciais': RouteRecordInfo<'/admin/relatorios/RelatoriosGerenciais', '/admin/relatorios/RelatoriosGerenciais', Record<never, never>, Record<never, never>>,
    '/admin/tickets/': RouteRecordInfo<'/admin/tickets/', '/admin/tickets', Record<never, never>, Record<never, never>>,
    '/admin/tickets/create-ticket': RouteRecordInfo<'/admin/tickets/create-ticket', '/admin/tickets/create-ticket', Record<never, never>, Record<never, never>>,
    '/admin/tickets/sla-config': RouteRecordInfo<'/admin/tickets/sla-config', '/admin/tickets/sla-config', Record<never, never>, Record<never, never>>,
    '/admin/tickets/sla-config-add': RouteRecordInfo<'/admin/tickets/sla-config-add', '/admin/tickets/sla-config-add', Record<never, never>, Record<never, never>>,
    '/admin/tickets/sla-config-update': RouteRecordInfo<'/admin/tickets/sla-config-update', '/admin/tickets/sla-config-update', Record<never, never>, Record<never, never>>,
    '/admin/tickets/ticket-details': RouteRecordInfo<'/admin/tickets/ticket-details', '/admin/tickets/ticket-details', Record<never, never>, Record<never, never>>,
    '/auth/': RouteRecordInfo<'/auth/', '/auth', Record<never, never>, Record<never, never>>,
  }
}
